records:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: spring_employee_records
    username: root
    password: 011688
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com

    bucketName: web-supercyan
